name: clean_architecture
description: Clean Architecture && SOLID Principle
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # Equality
  equatable: ^2.0.7
  # Dependency Injector
  get_it: ^8.0.3
  injectable: ^2.5.0
  # Network
  internet_connection_checker_plus: ^2.7.1
  http_parser: ^4.1.2
  dio: ^5.8.0+1
  alice_dio: ^1.0.6
  # Router
  auto_route: ^10.0.1
  # Local
  shared_preferences: ^2.5.3
  # State Management
  flutter_bloc: ^9.1.0
  flutter_hooks: ^0.21.2
  # UI
  flutter_sliding_toast: ^1.5.0
  # Util
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  auto_route_generator: ^10.0.1
  injectable_generator: ^2.7.0
  mocktail: ^1.0.4
  bloc_test: ^10.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

    - family: AppIcon
      fonts:
        - asset: assets/icons/AppIcon.ttf
